server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/allocation?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: developer$12

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
